project:
  type: website

website:
  title: "Simon Jones"
  page-navigation: true
  search:
    location: navbar
    type: textbox
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: slate
    css: styles.css
    toc: true
    highlight-style: gruvbox
